apiVersion: cert-manager.io/v1alpha2 
kind: ClusterIssuer
metadata:
  name: letsencrypt-ghost
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "test123@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-ghost
    solvers:
      - http01:
          ingress:
            class: nginx